astra_db:
  collection_name: "ecommdata"

embedding_model:
  provider: "openai"
  model_name: "text-embedding-3-small"

retriever:
  top_k: 3

llm:
  provider: "openai"
  model_name: "gpt-4o-mini-2024-07-18"

